
namespace Niu.Nutri.Livraria.Domain.Aggregates.LivrariaAgg.Queries.Models
{
    using Core.Api.Queries;
	using Enumerations;
	public partial class Livro_AutorQueryModel : BaseQueryModel {
		public int? Livro_CodlEqual { get; set; }
		public int? Livro_CodlNotEqual { get; set; }
		public int[]? Livro_CodlContains { get; set; }
		public int[]? Livro_CodlNotContains { get; set; }
		public int? Livro_CodlSince { get; set; }
		public int? Livro_CodlUntil { get; set; }
		public int? Livro_CodlLessThan { get; set; }
		public int? Livro_CodlGreaterThan { get; set; }
		public int? Livro_CodlLessThanOrEqual { get; set; }
		public int? Livro_CodlGreaterThanOrEqual { get; set; }
		public int? Autor_CodAutEqual { get; set; }
		public int? Autor_CodAutNotEqual { get; set; }
		public int[]? Autor_CodAutContains { get; set; }
		public int[]? Autor_CodAutNotContains { get; set; }
		public int? Autor_CodAutSince { get; set; }
		public int? Autor_CodAutUntil { get; set; }
		public int? Autor_CodAutLessThan { get; set; }
		public int? Autor_CodAutGreaterThan { get; set; }
		public int? Autor_CodAutLessThanOrEqual { get; set; }
		public int? Autor_CodAutGreaterThanOrEqual { get; set; }
		public string? IdExternoEqual { get; set; }
		public string? IdExternoNotEqual { get; set; }
		public string? IdExternoContains { get; set; }
		public string? IdExternoNotContains { get; set; }
		public string? IdExternoStartsWith { get; set; }
		public System.DateTime? CriadoEmEqual { get; set; }
		public System.DateTime? CriadoEmNotEqual { get; set; }
		public System.DateTime[]? CriadoEmContains { get; set; }
		public System.DateTime[]? CriadoEmNotContains { get; set; }
		public System.DateTime? CriadoEmSince { get; set; }
		public System.DateTime? CriadoEmUntil { get; set; }
		public System.DateTime? CriadoEmLessThan { get; set; }
		public System.DateTime? CriadoEmGreaterThan { get; set; }
		public System.DateTime? CriadoEmLessThanOrEqual { get; set; }
		public System.DateTime? CriadoEmGreaterThanOrEqual { get; set; }
		public System.DateTime? AtualizadoEmEqual { get; set; }
		public System.DateTime? AtualizadoEmNotEqual { get; set; }
		public System.DateTime[]? AtualizadoEmContains { get; set; }
		public System.DateTime[]? AtualizadoEmNotContains { get; set; }
		public System.DateTime? AtualizadoEmSince { get; set; }
		public System.DateTime? AtualizadoEmUntil { get; set; }
		public System.DateTime? AtualizadoEmLessThan { get; set; }
		public System.DateTime? AtualizadoEmGreaterThan { get; set; }
		public System.DateTime? AtualizadoEmLessThanOrEqual { get; set; }
		public System.DateTime? AtualizadoEmGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletadoEmEqual { get; set; }
		public System.DateTime? DeletadoEmNotEqual { get; set; }
		public System.DateTime[]? DeletadoEmContains { get; set; }
		public System.DateTime[]? DeletadoEmNotContains { get; set; }
		public System.DateTime? DeletadoEmSince { get; set; }
		public System.DateTime? DeletadoEmUntil { get; set; }
		public System.DateTime? DeletadoEmLessThan { get; set; }
		public System.DateTime? DeletadoEmGreaterThan { get; set; }
		public System.DateTime? DeletadoEmLessThanOrEqual { get; set; }
		public System.DateTime? DeletadoEmGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public bool? DeletadoEqual { get; set; }
	}
	public partial class LivroQueryModel : BaseQueryModel {
		public string? TituloEqual { get; set; }
		public string? TituloNotEqual { get; set; }
		public string? TituloContains { get; set; }
		public string? TituloNotContains { get; set; }
		public string? TituloStartsWith { get; set; }
		public string? EditoraEqual { get; set; }
		public string? EditoraNotEqual { get; set; }
		public string? EditoraContains { get; set; }
		public string? EditoraNotContains { get; set; }
		public string? EditoraStartsWith { get; set; }
		public string? EdicaoEqual { get; set; }
		public string? EdicaoNotEqual { get; set; }
		public string? EdicaoContains { get; set; }
		public string? EdicaoNotContains { get; set; }
		public string? EdicaoStartsWith { get; set; }
		public System.DateTime? AnoPublicacaoEqual { get; set; }
		public System.DateTime? AnoPublicacaoNotEqual { get; set; }
		public System.DateTime[]? AnoPublicacaoContains { get; set; }
		public System.DateTime[]? AnoPublicacaoNotContains { get; set; }
		public System.DateTime? AnoPublicacaoSince { get; set; }
		public System.DateTime? AnoPublicacaoUntil { get; set; }
		public System.DateTime? AnoPublicacaoLessThan { get; set; }
		public System.DateTime? AnoPublicacaoGreaterThan { get; set; }
		public System.DateTime? AnoPublicacaoLessThanOrEqual { get; set; }
		public System.DateTime? AnoPublicacaoGreaterThanOrEqual { get; set; }
		public string? IdExternoEqual { get; set; }
		public string? IdExternoNotEqual { get; set; }
		public string? IdExternoContains { get; set; }
		public string? IdExternoNotContains { get; set; }
		public string? IdExternoStartsWith { get; set; }
		public System.DateTime? CriadoEmEqual { get; set; }
		public System.DateTime? CriadoEmNotEqual { get; set; }
		public System.DateTime[]? CriadoEmContains { get; set; }
		public System.DateTime[]? CriadoEmNotContains { get; set; }
		public System.DateTime? CriadoEmSince { get; set; }
		public System.DateTime? CriadoEmUntil { get; set; }
		public System.DateTime? CriadoEmLessThan { get; set; }
		public System.DateTime? CriadoEmGreaterThan { get; set; }
		public System.DateTime? CriadoEmLessThanOrEqual { get; set; }
		public System.DateTime? CriadoEmGreaterThanOrEqual { get; set; }
		public System.DateTime? AtualizadoEmEqual { get; set; }
		public System.DateTime? AtualizadoEmNotEqual { get; set; }
		public System.DateTime[]? AtualizadoEmContains { get; set; }
		public System.DateTime[]? AtualizadoEmNotContains { get; set; }
		public System.DateTime? AtualizadoEmSince { get; set; }
		public System.DateTime? AtualizadoEmUntil { get; set; }
		public System.DateTime? AtualizadoEmLessThan { get; set; }
		public System.DateTime? AtualizadoEmGreaterThan { get; set; }
		public System.DateTime? AtualizadoEmLessThanOrEqual { get; set; }
		public System.DateTime? AtualizadoEmGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletadoEmEqual { get; set; }
		public System.DateTime? DeletadoEmNotEqual { get; set; }
		public System.DateTime[]? DeletadoEmContains { get; set; }
		public System.DateTime[]? DeletadoEmNotContains { get; set; }
		public System.DateTime? DeletadoEmSince { get; set; }
		public System.DateTime? DeletadoEmUntil { get; set; }
		public System.DateTime? DeletadoEmLessThan { get; set; }
		public System.DateTime? DeletadoEmGreaterThan { get; set; }
		public System.DateTime? DeletadoEmLessThanOrEqual { get; set; }
		public System.DateTime? DeletadoEmGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public bool? DeletadoEqual { get; set; }
	}
	public partial class AssuntoQueryModel : BaseQueryModel {
		public string? DescricaoEqual { get; set; }
		public string? DescricaoNotEqual { get; set; }
		public string? DescricaoContains { get; set; }
		public string? DescricaoNotContains { get; set; }
		public string? DescricaoStartsWith { get; set; }
		public string? IdExternoEqual { get; set; }
		public string? IdExternoNotEqual { get; set; }
		public string? IdExternoContains { get; set; }
		public string? IdExternoNotContains { get; set; }
		public string? IdExternoStartsWith { get; set; }
		public System.DateTime? CriadoEmEqual { get; set; }
		public System.DateTime? CriadoEmNotEqual { get; set; }
		public System.DateTime[]? CriadoEmContains { get; set; }
		public System.DateTime[]? CriadoEmNotContains { get; set; }
		public System.DateTime? CriadoEmSince { get; set; }
		public System.DateTime? CriadoEmUntil { get; set; }
		public System.DateTime? CriadoEmLessThan { get; set; }
		public System.DateTime? CriadoEmGreaterThan { get; set; }
		public System.DateTime? CriadoEmLessThanOrEqual { get; set; }
		public System.DateTime? CriadoEmGreaterThanOrEqual { get; set; }
		public System.DateTime? AtualizadoEmEqual { get; set; }
		public System.DateTime? AtualizadoEmNotEqual { get; set; }
		public System.DateTime[]? AtualizadoEmContains { get; set; }
		public System.DateTime[]? AtualizadoEmNotContains { get; set; }
		public System.DateTime? AtualizadoEmSince { get; set; }
		public System.DateTime? AtualizadoEmUntil { get; set; }
		public System.DateTime? AtualizadoEmLessThan { get; set; }
		public System.DateTime? AtualizadoEmGreaterThan { get; set; }
		public System.DateTime? AtualizadoEmLessThanOrEqual { get; set; }
		public System.DateTime? AtualizadoEmGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletadoEmEqual { get; set; }
		public System.DateTime? DeletadoEmNotEqual { get; set; }
		public System.DateTime[]? DeletadoEmContains { get; set; }
		public System.DateTime[]? DeletadoEmNotContains { get; set; }
		public System.DateTime? DeletadoEmSince { get; set; }
		public System.DateTime? DeletadoEmUntil { get; set; }
		public System.DateTime? DeletadoEmLessThan { get; set; }
		public System.DateTime? DeletadoEmGreaterThan { get; set; }
		public System.DateTime? DeletadoEmLessThanOrEqual { get; set; }
		public System.DateTime? DeletadoEmGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public bool? DeletadoEqual { get; set; }
	}
	public partial class Livro_AssuntoQueryModel : BaseQueryModel {
		public int? Livro_CodlEqual { get; set; }
		public int? Livro_CodlNotEqual { get; set; }
		public int[]? Livro_CodlContains { get; set; }
		public int[]? Livro_CodlNotContains { get; set; }
		public int? Livro_CodlSince { get; set; }
		public int? Livro_CodlUntil { get; set; }
		public int? Livro_CodlLessThan { get; set; }
		public int? Livro_CodlGreaterThan { get; set; }
		public int? Livro_CodlLessThanOrEqual { get; set; }
		public int? Livro_CodlGreaterThanOrEqual { get; set; }
		public int? Assunto_CodAutEqual { get; set; }
		public int? Assunto_CodAutNotEqual { get; set; }
		public int[]? Assunto_CodAutContains { get; set; }
		public int[]? Assunto_CodAutNotContains { get; set; }
		public int? Assunto_CodAutSince { get; set; }
		public int? Assunto_CodAutUntil { get; set; }
		public int? Assunto_CodAutLessThan { get; set; }
		public int? Assunto_CodAutGreaterThan { get; set; }
		public int? Assunto_CodAutLessThanOrEqual { get; set; }
		public int? Assunto_CodAutGreaterThanOrEqual { get; set; }
		public string? IdExternoEqual { get; set; }
		public string? IdExternoNotEqual { get; set; }
		public string? IdExternoContains { get; set; }
		public string? IdExternoNotContains { get; set; }
		public string? IdExternoStartsWith { get; set; }
		public System.DateTime? CriadoEmEqual { get; set; }
		public System.DateTime? CriadoEmNotEqual { get; set; }
		public System.DateTime[]? CriadoEmContains { get; set; }
		public System.DateTime[]? CriadoEmNotContains { get; set; }
		public System.DateTime? CriadoEmSince { get; set; }
		public System.DateTime? CriadoEmUntil { get; set; }
		public System.DateTime? CriadoEmLessThan { get; set; }
		public System.DateTime? CriadoEmGreaterThan { get; set; }
		public System.DateTime? CriadoEmLessThanOrEqual { get; set; }
		public System.DateTime? CriadoEmGreaterThanOrEqual { get; set; }
		public System.DateTime? AtualizadoEmEqual { get; set; }
		public System.DateTime? AtualizadoEmNotEqual { get; set; }
		public System.DateTime[]? AtualizadoEmContains { get; set; }
		public System.DateTime[]? AtualizadoEmNotContains { get; set; }
		public System.DateTime? AtualizadoEmSince { get; set; }
		public System.DateTime? AtualizadoEmUntil { get; set; }
		public System.DateTime? AtualizadoEmLessThan { get; set; }
		public System.DateTime? AtualizadoEmGreaterThan { get; set; }
		public System.DateTime? AtualizadoEmLessThanOrEqual { get; set; }
		public System.DateTime? AtualizadoEmGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletadoEmEqual { get; set; }
		public System.DateTime? DeletadoEmNotEqual { get; set; }
		public System.DateTime[]? DeletadoEmContains { get; set; }
		public System.DateTime[]? DeletadoEmNotContains { get; set; }
		public System.DateTime? DeletadoEmSince { get; set; }
		public System.DateTime? DeletadoEmUntil { get; set; }
		public System.DateTime? DeletadoEmLessThan { get; set; }
		public System.DateTime? DeletadoEmGreaterThan { get; set; }
		public System.DateTime? DeletadoEmLessThanOrEqual { get; set; }
		public System.DateTime? DeletadoEmGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public bool? DeletadoEqual { get; set; }
	}
	public partial class AutorQueryModel : BaseQueryModel {
		public string? NomeEqual { get; set; }
		public string? NomeNotEqual { get; set; }
		public string? NomeContains { get; set; }
		public string? NomeNotContains { get; set; }
		public string? NomeStartsWith { get; set; }
		public string? IdExternoEqual { get; set; }
		public string? IdExternoNotEqual { get; set; }
		public string? IdExternoContains { get; set; }
		public string? IdExternoNotContains { get; set; }
		public string? IdExternoStartsWith { get; set; }
		public System.DateTime? CriadoEmEqual { get; set; }
		public System.DateTime? CriadoEmNotEqual { get; set; }
		public System.DateTime[]? CriadoEmContains { get; set; }
		public System.DateTime[]? CriadoEmNotContains { get; set; }
		public System.DateTime? CriadoEmSince { get; set; }
		public System.DateTime? CriadoEmUntil { get; set; }
		public System.DateTime? CriadoEmLessThan { get; set; }
		public System.DateTime? CriadoEmGreaterThan { get; set; }
		public System.DateTime? CriadoEmLessThanOrEqual { get; set; }
		public System.DateTime? CriadoEmGreaterThanOrEqual { get; set; }
		public System.DateTime? AtualizadoEmEqual { get; set; }
		public System.DateTime? AtualizadoEmNotEqual { get; set; }
		public System.DateTime[]? AtualizadoEmContains { get; set; }
		public System.DateTime[]? AtualizadoEmNotContains { get; set; }
		public System.DateTime? AtualizadoEmSince { get; set; }
		public System.DateTime? AtualizadoEmUntil { get; set; }
		public System.DateTime? AtualizadoEmLessThan { get; set; }
		public System.DateTime? AtualizadoEmGreaterThan { get; set; }
		public System.DateTime? AtualizadoEmLessThanOrEqual { get; set; }
		public System.DateTime? AtualizadoEmGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletadoEmEqual { get; set; }
		public System.DateTime? DeletadoEmNotEqual { get; set; }
		public System.DateTime[]? DeletadoEmContains { get; set; }
		public System.DateTime[]? DeletadoEmNotContains { get; set; }
		public System.DateTime? DeletadoEmSince { get; set; }
		public System.DateTime? DeletadoEmUntil { get; set; }
		public System.DateTime? DeletadoEmLessThan { get; set; }
		public System.DateTime? DeletadoEmGreaterThan { get; set; }
		public System.DateTime? DeletadoEmLessThanOrEqual { get; set; }
		public System.DateTime? DeletadoEmGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public bool? DeletadoEqual { get; set; }
	}
	public partial class LivrariaAggSettingsQueryModel : BaseQueryModel {
		public bool? AutoSaveSettingsEnabledEqual { get; set; }
		public string? IdExternoEqual { get; set; }
		public string? IdExternoNotEqual { get; set; }
		public string? IdExternoContains { get; set; }
		public string? IdExternoNotContains { get; set; }
		public string? IdExternoStartsWith { get; set; }
		public System.DateTime? CriadoEmEqual { get; set; }
		public System.DateTime? CriadoEmNotEqual { get; set; }
		public System.DateTime[]? CriadoEmContains { get; set; }
		public System.DateTime[]? CriadoEmNotContains { get; set; }
		public System.DateTime? CriadoEmSince { get; set; }
		public System.DateTime? CriadoEmUntil { get; set; }
		public System.DateTime? CriadoEmLessThan { get; set; }
		public System.DateTime? CriadoEmGreaterThan { get; set; }
		public System.DateTime? CriadoEmLessThanOrEqual { get; set; }
		public System.DateTime? CriadoEmGreaterThanOrEqual { get; set; }
		public System.DateTime? AtualizadoEmEqual { get; set; }
		public System.DateTime? AtualizadoEmNotEqual { get; set; }
		public System.DateTime[]? AtualizadoEmContains { get; set; }
		public System.DateTime[]? AtualizadoEmNotContains { get; set; }
		public System.DateTime? AtualizadoEmSince { get; set; }
		public System.DateTime? AtualizadoEmUntil { get; set; }
		public System.DateTime? AtualizadoEmLessThan { get; set; }
		public System.DateTime? AtualizadoEmGreaterThan { get; set; }
		public System.DateTime? AtualizadoEmLessThanOrEqual { get; set; }
		public System.DateTime? AtualizadoEmGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletadoEmEqual { get; set; }
		public System.DateTime? DeletadoEmNotEqual { get; set; }
		public System.DateTime[]? DeletadoEmContains { get; set; }
		public System.DateTime[]? DeletadoEmNotContains { get; set; }
		public System.DateTime? DeletadoEmSince { get; set; }
		public System.DateTime? DeletadoEmUntil { get; set; }
		public System.DateTime? DeletadoEmLessThan { get; set; }
		public System.DateTime? DeletadoEmGreaterThan { get; set; }
		public System.DateTime? DeletadoEmLessThanOrEqual { get; set; }
		public System.DateTime? DeletadoEmGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public bool? DeletadoEqual { get; set; }
	}
}
