using Niu.Nutri.Chat.Domain.Aggregates.UsersAgg.Entities;
using Niu.Nutri.Chat.Enumerations;
using Niu.Nutri.Core.Application.DTO.Attributes;
using Niu.Nutri.Core.Domain.Aggregates.CommonAgg.Entities;
using Niu.Nutri.Core.Domain.Attributes.T4;

namespace Niu.Nutri.Chat.Domain.Aggregates.ChatAgg.Entities
{
    [EndpointsT4(EndpointTypes.HttpAll), AutoGenerateDefaultFiles]
    public partial class ConversationMessage : Entity
    {
        public string Text { get; set; }

        public MessageStatus Status { get; set; }

        public int ConversationId { get; set; }

        [IgnorePropertyT4]
        public virtual User From { get; set; }

        public int FromId { get; set; }
    }
}
