using Niu.Nutri.Chat.Domain.Aggregates.UsersAgg.Entities;
using Niu.Nutri.Core.Application.DTO.Attributes;
using Niu.Nutri.Core.Domain.Aggregates.CommonAgg.Entities;
using Niu.Nutri.Core.Domain.Attributes.T4;
using StackExchange.Redis;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Niu.Nutri.Chat.Domain.Aggregates.ChatAgg.Entities
{
    [Steppable(1), DoNotReplaceAfterGenerated]
    [EndpointsT4(EndpointTypes.HttpAll), AutoGenerateDefaultFiles]
    public partial class Conversation : SteppableEntity
    {
        [IgnorePropertyT4]
        public User From { get; set; }

        [DisplayName("")]
        [DisplayOnList]
        public string? FromAvatar => From?.ProfilePicture;

        [DisplayName("Remetente")]
        [DisplayOnList]
        public string? FromName => From?.Name;

        [DisplayOnList]
        [DisplayName("Qtd Mensagens")]
        public int MessagesCount => Messages?.Count ?? 0;

        [DisplayOnList]
        [DisplayName("Mensagens N�o Lidas")]
        public int? NotReadMessagesCount => Messages?.Count(x=>x.Status == Enumerations.MessageStatus.Sent) ?? 0;


        [Required]
        public int FromId { get; set; }

        [IgnorePropertyT4]
        public User To { get; set; }

        [Required]
        public int ToId { get; set; }

        public virtual List<ConversationMessage> Messages { get; set; }
    }
}
