// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Niu.Nutri.SystemSettings.Infra.Data.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Niu.Nutri.SystemSettings.Infra.Data.Migrations
{
    [DbContext(typeof(SystemSettingsAggContext))]
    [Migration("20240501062142_2024_5_1_3_12_16")]
    partial class _2024_5_1_3_12_16
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Niu.Nutri.SystemSettings.Domain.Aggregates.SystemSettingsAgg.Entities.CargaTabela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("ArquivoCSV")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInitialized")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RegisterDone")
                        .HasColumnType("boolean");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Total")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CargaTabela");
                });

            modelBuilder.Entity("Niu.Nutri.SystemSettings.Domain.Aggregates.SystemSettingsAgg.Entities.SystemPanel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RegisterDone")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SystemPanel");
                });

            modelBuilder.Entity("Niu.Nutri.SystemSettings.Domain.Aggregates.SystemSettingsAgg.Entities.SystemPanelGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RegisterDone")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SystemPanelGroup");
                });

            modelBuilder.Entity("Niu.Nutri.SystemSettings.Domain.Aggregates.SystemSettingsAgg.Entities.SystemPanelSubItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ActionButton")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("AssemblyDrillComponent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSubItem")
                        .HasColumnType("boolean");

                    b.Property<bool>("LinkDireto")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RegisterDone")
                        .HasColumnType("boolean");

                    b.Property<int>("SystemPanelId")
                        .HasColumnType("integer");

                    b.Property<int?>("SystemPanelSubItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SystemPanelId");

                    b.HasIndex("SystemPanelSubItemId");

                    b.ToTable("SystemPanelSubItem");
                });

            modelBuilder.Entity("Niu.Nutri.SystemSettings.Domain.Aggregates.SystemSettingsAgg.Entities.SystemSettingsAggSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoSaveSettingsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SystemSettingsAggSettings");
                });

            modelBuilder.Entity("Niu.Nutri.SystemSettings.Domain.Aggregates.UsersAgg.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("User", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Niu.Nutri.SystemSettings.Domain.Aggregates.UsersAgg.Entities.UserProfileAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanInsert")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanList")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSubItem")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<bool?>("RegisterDone")
                        .HasColumnType("boolean");

                    b.Property<int?>("SystemPanelGroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("SystemPanelId")
                        .HasColumnType("integer");

                    b.Property<int?>("SystemPanelSubItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SystemPanelGroupId");

                    b.HasIndex("SystemPanelId");

                    b.ToTable("UserProfileAccess", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SystemPanelGroupSystemPanel", b =>
                {
                    b.Property<int>("GroupOfMenusId")
                        .HasColumnType("integer");

                    b.Property<int>("SubItemsId")
                        .HasColumnType("integer");

                    b.HasKey("GroupOfMenusId", "SubItemsId");

                    b.HasIndex("SubItemsId");

                    b.ToTable("SystemPanelGroupSystemPanel");
                });

            modelBuilder.Entity("Niu.Nutri.SystemSettings.Domain.Aggregates.SystemSettingsAgg.Entities.SystemPanelSubItem", b =>
                {
                    b.HasOne("Niu.Nutri.SystemSettings.Domain.Aggregates.SystemSettingsAgg.Entities.SystemPanel", null)
                        .WithMany("SubItems")
                        .HasForeignKey("SystemPanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Niu.Nutri.SystemSettings.Domain.Aggregates.SystemSettingsAgg.Entities.SystemPanelSubItem", null)
                        .WithMany("SubItems")
                        .HasForeignKey("SystemPanelSubItemId");
                });

            modelBuilder.Entity("Niu.Nutri.SystemSettings.Domain.Aggregates.UsersAgg.Entities.UserProfileAccess", b =>
                {
                    b.HasOne("Niu.Nutri.SystemSettings.Domain.Aggregates.SystemSettingsAgg.Entities.SystemPanelGroup", null)
                        .WithMany("AccessesOfMyProfile")
                        .HasForeignKey("SystemPanelGroupId");

                    b.HasOne("Niu.Nutri.SystemSettings.Domain.Aggregates.SystemSettingsAgg.Entities.SystemPanel", null)
                        .WithMany("AccessesOfMyProfile")
                        .HasForeignKey("SystemPanelId");
                });

            modelBuilder.Entity("SystemPanelGroupSystemPanel", b =>
                {
                    b.HasOne("Niu.Nutri.SystemSettings.Domain.Aggregates.SystemSettingsAgg.Entities.SystemPanelGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupOfMenusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Niu.Nutri.SystemSettings.Domain.Aggregates.SystemSettingsAgg.Entities.SystemPanel", null)
                        .WithMany()
                        .HasForeignKey("SubItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Niu.Nutri.SystemSettings.Domain.Aggregates.SystemSettingsAgg.Entities.SystemPanel", b =>
                {
                    b.Navigation("AccessesOfMyProfile");

                    b.Navigation("SubItems");
                });

            modelBuilder.Entity("Niu.Nutri.SystemSettings.Domain.Aggregates.SystemSettingsAgg.Entities.SystemPanelGroup", b =>
                {
                    b.Navigation("AccessesOfMyProfile");
                });

            modelBuilder.Entity("Niu.Nutri.SystemSettings.Domain.Aggregates.SystemSettingsAgg.Entities.SystemPanelSubItem", b =>
                {
                    b.Navigation("SubItems");
                });
#pragma warning restore 612, 618
        }
    }
}
