
namespace Niu.Nutri.Addresses.Domain.Aggregates.AddressesAgg.Queries.Models
{
    using Core.Api.Queries;
	using Enumerations;
	public partial class AddressQueryModel : BaseQueryModel {
		public string? CEPEqual { get; set; }
		public string? CEPNotEqual { get; set; }
		public string? CEPContains { get; set; }
		public string? CEPNotContains { get; set; }
		public string? CEPStartsWith { get; set; }
		public string? LogradouroEqual { get; set; }
		public string? LogradouroNotEqual { get; set; }
		public string? LogradouroContains { get; set; }
		public string? LogradouroNotContains { get; set; }
		public string? LogradouroStartsWith { get; set; }
		public string? TipoLogradouroEqual { get; set; }
		public string? TipoLogradouroNotEqual { get; set; }
		public string? TipoLogradouroContains { get; set; }
		public string? TipoLogradouroNotContains { get; set; }
		public string? TipoLogradouroStartsWith { get; set; }
		public string? Bairro_DistritoEqual { get; set; }
		public string? Bairro_DistritoNotEqual { get; set; }
		public string? Bairro_DistritoContains { get; set; }
		public string? Bairro_DistritoNotContains { get; set; }
		public string? Bairro_DistritoStartsWith { get; set; }
		public string? Cidade_LocalidadeEqual { get; set; }
		public string? Cidade_LocalidadeNotEqual { get; set; }
		public string? Cidade_LocalidadeContains { get; set; }
		public string? Cidade_LocalidadeNotContains { get; set; }
		public string? Cidade_LocalidadeStartsWith { get; set; }
		public string? UFEqual { get; set; }
		public string? UFNotEqual { get; set; }
		public string? UFContains { get; set; }
		public string? UFNotContains { get; set; }
		public string? UFStartsWith { get; set; }
		public double? LatEqual { get; set; }
		public double? LatNotEqual { get; set; }
		public double[]? LatContains { get; set; }
		public double[]? LatNotContains { get; set; }
		public double? LatSince { get; set; }
		public double? LatUntil { get; set; }
		public double? LatLessThan { get; set; }
		public double? LatGreaterThan { get; set; }
		public double? LatLessThanOrEqual { get; set; }
		public double? LatGreaterThanOrEqual { get; set; }
		public double? LngEqual { get; set; }
		public double? LngNotEqual { get; set; }
		public double[]? LngContains { get; set; }
		public double[]? LngNotContains { get; set; }
		public double? LngSince { get; set; }
		public double? LngUntil { get; set; }
		public double? LngLessThan { get; set; }
		public double? LngGreaterThan { get; set; }
		public double? LngLessThanOrEqual { get; set; }
		public double? LngGreaterThanOrEqual { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdNotContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class AddressesAggSettingsQueryModel : BaseQueryModel {
		public int? UserIdEqual { get; set; }
		public int? UserIdNotEqual { get; set; }
		public int[]? UserIdContains { get; set; }
		public int[]? UserIdNotContains { get; set; }
		public int? UserIdSince { get; set; }
		public int? UserIdUntil { get; set; }
		public int? UserIdLessThan { get; set; }
		public int? UserIdGreaterThan { get; set; }
		public int? UserIdLessThanOrEqual { get; set; }
		public int? UserIdGreaterThanOrEqual { get; set; }
		public bool? AutoSaveSettingsEnabledEqual { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdNotContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
