using Niu.Nutri.Core.Application.DTO.Attributes;
using Niu.Nutri.Core.Domain.Aggregates.CommonAgg.Entities;
using Niu.Nutri.Core.Domain.Attributes.T4;

namespace Niu.Nutri.Addresses.Domain.Aggregates.AddressesAgg.Entities
{
    [EndpointsT4(EndpointTypes.HttpAll), AutoGenerateDefaultFiles]
    public partial class Address : Entity
    {
        [RequiredT4, Title]
        public string? CEP { get; set; }
        [RequiredT4]
        public string? Logradouro { get; set; }
        [RequiredT4]
        public string? TipoLogradouro { get; set; }
        [RequiredT4]
        public string? Bairro_Distrito { get; set; }
        [RequiredT4, Unique]
        public string? Cidade_Localidade { get; set; }
        [RequiredT4]
        public string? UF { get; set; }

        public double Lat {  get; set; }
        public double Lng { get; set; }
    }
}
