
namespace Niu.Nutri.Chat.Domain.Aggregates.ChatAgg.Queries.Models
{
    using Core.Api.Queries;
	using Enumerations;
	public partial class ConversationQueryModel : BaseQueryModel {
		public string? FromAvatarEqual { get; set; }
		public string? FromAvatarNotEqual { get; set; }
		public string? FromAvatarContains { get; set; }
		public string? FromAvatarNotContains { get; set; }
		public string? FromAvatarStartsWith { get; set; }
		public string? FromNameEqual { get; set; }
		public string? FromNameNotEqual { get; set; }
		public string? FromNameContains { get; set; }
		public string? FromNameNotContains { get; set; }
		public string? FromNameStartsWith { get; set; }
		public int? MessagesCountEqual { get; set; }
		public int? MessagesCountNotEqual { get; set; }
		public int[]? MessagesCountContains { get; set; }
		public int[]? MessagesCountNotContains { get; set; }
		public int? MessagesCountSince { get; set; }
		public int? MessagesCountUntil { get; set; }
		public int? MessagesCountLessThan { get; set; }
		public int? MessagesCountGreaterThan { get; set; }
		public int? MessagesCountLessThanOrEqual { get; set; }
		public int? MessagesCountGreaterThanOrEqual { get; set; }
		public int? NotReadMessagesCountEqual { get; set; }
		public int? NotReadMessagesCountNotEqual { get; set; }
		public int[]? NotReadMessagesCountContains { get; set; }
		public int[]? NotReadMessagesCountNotContains { get; set; }
		public int? NotReadMessagesCountSince { get; set; }
		public int? NotReadMessagesCountUntil { get; set; }
		public int? NotReadMessagesCountLessThan { get; set; }
		public int? NotReadMessagesCountGreaterThan { get; set; }
		public int? NotReadMessagesCountLessThanOrEqual { get; set; }
		public int? NotReadMessagesCountGreaterThanOrEqual { get; set; }
		public int? FromIdEqual { get; set; }
		public int? FromIdNotEqual { get; set; }
		public int[]? FromIdContains { get; set; }
		public int[]? FromIdNotContains { get; set; }
		public int? FromIdSince { get; set; }
		public int? FromIdUntil { get; set; }
		public int? FromIdLessThan { get; set; }
		public int? FromIdGreaterThan { get; set; }
		public int? FromIdLessThanOrEqual { get; set; }
		public int? FromIdGreaterThanOrEqual { get; set; }
		public int? ToIdEqual { get; set; }
		public int? ToIdNotEqual { get; set; }
		public int[]? ToIdContains { get; set; }
		public int[]? ToIdNotContains { get; set; }
		public int? ToIdSince { get; set; }
		public int? ToIdUntil { get; set; }
		public int? ToIdLessThan { get; set; }
		public int? ToIdGreaterThan { get; set; }
		public int? ToIdLessThanOrEqual { get; set; }
		public int? ToIdGreaterThanOrEqual { get; set; }
		public int? CurrentStepEqual { get; set; }
		public int? CurrentStepNotEqual { get; set; }
		public int[]? CurrentStepContains { get; set; }
		public int[]? CurrentStepNotContains { get; set; }
		public int? CurrentStepSince { get; set; }
		public int? CurrentStepUntil { get; set; }
		public int? CurrentStepLessThan { get; set; }
		public int? CurrentStepGreaterThan { get; set; }
		public int? CurrentStepLessThanOrEqual { get; set; }
		public int? CurrentStepGreaterThanOrEqual { get; set; }
		public int? MaxStepsEqual { get; set; }
		public int? MaxStepsNotEqual { get; set; }
		public int[]? MaxStepsContains { get; set; }
		public int[]? MaxStepsNotContains { get; set; }
		public int? MaxStepsSince { get; set; }
		public int? MaxStepsUntil { get; set; }
		public int? MaxStepsLessThan { get; set; }
		public int? MaxStepsGreaterThan { get; set; }
		public int? MaxStepsLessThanOrEqual { get; set; }
		public int? MaxStepsGreaterThanOrEqual { get; set; }
		public bool? RegisterDoneEqual { get; set; }
		public bool? ActiveEqual { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdNotContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class ChatAggSettingsQueryModel : BaseQueryModel {
		public int? UserIdEqual { get; set; }
		public int? UserIdNotEqual { get; set; }
		public int[]? UserIdContains { get; set; }
		public int[]? UserIdNotContains { get; set; }
		public int? UserIdSince { get; set; }
		public int? UserIdUntil { get; set; }
		public int? UserIdLessThan { get; set; }
		public int? UserIdGreaterThan { get; set; }
		public int? UserIdLessThanOrEqual { get; set; }
		public int? UserIdGreaterThanOrEqual { get; set; }
		public bool? AutoSaveSettingsEnabledEqual { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdNotContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
	public partial class ConversationMessageQueryModel : BaseQueryModel {
		public string? TextEqual { get; set; }
		public string? TextNotEqual { get; set; }
		public string? TextContains { get; set; }
		public string? TextNotContains { get; set; }
		public string? TextStartsWith { get; set; }
		public Niu.Nutri.Chat.Enumerations.MessageStatus? StatusEqual { get; set; }
		public int? ConversationIdEqual { get; set; }
		public int? ConversationIdNotEqual { get; set; }
		public int[]? ConversationIdContains { get; set; }
		public int[]? ConversationIdNotContains { get; set; }
		public int? ConversationIdSince { get; set; }
		public int? ConversationIdUntil { get; set; }
		public int? ConversationIdLessThan { get; set; }
		public int? ConversationIdGreaterThan { get; set; }
		public int? ConversationIdLessThanOrEqual { get; set; }
		public int? ConversationIdGreaterThanOrEqual { get; set; }
		public int? FromIdEqual { get; set; }
		public int? FromIdNotEqual { get; set; }
		public int[]? FromIdContains { get; set; }
		public int[]? FromIdNotContains { get; set; }
		public int? FromIdSince { get; set; }
		public int? FromIdUntil { get; set; }
		public int? FromIdLessThan { get; set; }
		public int? FromIdGreaterThan { get; set; }
		public int? FromIdLessThanOrEqual { get; set; }
		public int? FromIdGreaterThanOrEqual { get; set; }
		public string? ExternalIdEqual { get; set; }
		public string? ExternalIdNotEqual { get; set; }
		public string? ExternalIdContains { get; set; }
		public string? ExternalIdNotContains { get; set; }
		public string? ExternalIdStartsWith { get; set; }
		public System.DateTime? CreatedAtEqual { get; set; }
		public System.DateTime? CreatedAtNotEqual { get; set; }
		public System.DateTime[]? CreatedAtContains { get; set; }
		public System.DateTime[]? CreatedAtNotContains { get; set; }
		public System.DateTime? CreatedAtSince { get; set; }
		public System.DateTime? CreatedAtUntil { get; set; }
		public System.DateTime? CreatedAtLessThan { get; set; }
		public System.DateTime? CreatedAtGreaterThan { get; set; }
		public System.DateTime? CreatedAtLessThanOrEqual { get; set; }
		public System.DateTime? CreatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtEqual { get; set; }
		public System.DateTime? UpdatedAtNotEqual { get; set; }
		public System.DateTime[]? UpdatedAtContains { get; set; }
		public System.DateTime[]? UpdatedAtNotContains { get; set; }
		public System.DateTime? UpdatedAtSince { get; set; }
		public System.DateTime? UpdatedAtUntil { get; set; }
		public System.DateTime? UpdatedAtLessThan { get; set; }
		public System.DateTime? UpdatedAtGreaterThan { get; set; }
		public System.DateTime? UpdatedAtLessThanOrEqual { get; set; }
		public System.DateTime? UpdatedAtGreaterThanOrEqual { get; set; }
		public System.DateTime? DeletedAtEqual { get; set; }
		public System.DateTime? DeletedAtNotEqual { get; set; }
		public System.DateTime[]? DeletedAtContains { get; set; }
		public System.DateTime[]? DeletedAtNotContains { get; set; }
		public System.DateTime? DeletedAtSince { get; set; }
		public System.DateTime? DeletedAtUntil { get; set; }
		public System.DateTime? DeletedAtLessThan { get; set; }
		public System.DateTime? DeletedAtGreaterThan { get; set; }
		public System.DateTime? DeletedAtLessThanOrEqual { get; set; }
		public System.DateTime? DeletedAtGreaterThanOrEqual { get; set; }
		public int? IdEqual { get; set; }
		public int? IdNotEqual { get; set; }
		public int[]? IdContains { get; set; }
		public int[]? IdNotContains { get; set; }
		public bool? IsDeletedEqual { get; set; }
	}
}
