using Niu.Nutri.Core.Application.DTO.Attributes;
using Niu.Nutri.Core.Domain.Aggregates.CommonAgg.Entities;
using Niu.Nutri.Core.Domain.Attributes.T4;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Niu.Nutri.Livraria.Domain.Aggregates.LivrariaAgg.Entities;

[EndpointsT4(EndpointTypes.HttpAll), AutoGenerateDefaultFiles]
public partial class Book : Entity
{
    [Required]
    [StringLength(40)]
    public string Title { get; set; }

    [Required]
    [StringLength(40)]
    public string Publisher { get; set; }

    public int? Edition { get; set; } = 1;

    [Required]
    public DateTime AnoPublicacao { get; set; }

    public List<Author> Authors { get; set; } = new();

    public List<Subject> Subjects { get; set; } = new();
}
