using Niu.Nutri.Core.Domain.Attributes.T4;
using Niu.Nutri.Core.Domain.Aggregates.CommonAgg.Entities;
using System.ComponentModel.DataAnnotations;
using Niu.Nutri.Core.Application.DTO.Attributes;

namespace Niu.Nutri.Livraria.Domain.Aggregates.LivrariaAgg.Entities;

[EndpointsT4(EndpointTypes.HttpAll), AutoGenerateDefaultFiles]
public partial class Livro : Entity
{
    [StringLength(4)]
    [Required]
    public string Titulo { get; set; }

    [Required]
    public string Editora { get; set; }

    [Required]
    public string Edicao { get; set; }

    [Required]
    public DateTime AnoPublicacao { get; set; }

    public List<Autor> Autores { get; set; } = new();

    public List<Assunto> Assuntos { get; set; } = new();
}
