using Niu.Nutri.Core.Application.DTO.Attributes;
using Niu.Nutri.Core.Domain.Aggregates.CommonAgg.Entities;
using Niu.Nutri.Core.Domain.Attributes.T4;
using System.ComponentModel.DataAnnotations;

namespace Niu.Nutri.Livraria.Domain.Aggregates.LivrariaAgg.Entities;

[EndpointsT4(EndpointTypes.HttpAll), AutoGenerateDefaultFiles]
public partial class Livro : Entity
{
    [Required]
    [StringLength(40)]
    public string Titulo { get; set; }

    [Required]
    [StringLength(40)]
    public string Editora { get; set; }

    public int? Edicao { get; set; } = 1;

    [Required]
    public DateTime AnoPublicacao { get; set; }

    public List<Autor> Autores { get; set; } = new();

    public List<Assunto> Assuntos { get; set; } = new();
}
